### ISSUE TITLE
Cloning copies prototype properties onto the object

### ISSUE THREAD

**Issue by dwelle** [lukeed/klona#14]
```js
function Test () {}
Test.prototype.val = 42;

console.log(klona(new Test())); // { val: 42 }
console.log(klona(new Test()).__proto__); // {}
```

**Comment by lukeed** [comment]
Thank you

This will be included in the default & upcoming "full" modes.

**Comment by evilebottnawi** [comment]
@lukeed can we fix it? Blocker for fully migrate on klona

**Comment by lukeed** [comment]
Yup, I have a solution to this now. Had to spend some time on it so that performance didn't take too much of a blow.

This will be included in 1.1.2 and then I will immediately begin moving to 2.0.0 with #13 in mind.

**Comment by lukeed** [comment]
Hey @evilebottnawi – I'm not sure what you're switching from, but I'm guessing it's `clone-deep`. Just wanted to let you know that `clone-deep` never actually _clones_ a custom class instance unless you explicitly tell it to. By default, it returned the original instance. Only `lodash` – and now `klona` – return a new fresh instance of the custom class by default. 

You can see this here:

```js
const clone = require('clone-deep');
const klona = require('klona');

function Test () {}
Test.prototype.val = 42;

function run(name, lib) {
	let input = new Test();
	let output = lib(input);

	console.log('[%s] before:', name, output.val);
	input.val++; // modify source
	console.log('[%s] after:', name, output.val);
}

run('clone-deep', clone);
run('clone-deep (instance)', foo => clone(foo, true));
run('klona', klona);

//=> [clone-deep] before: 42
//=> [clone-deep] after: 43
//=> [clone-deep (instance)] before: 42
//=> [clone-deep (instance)] after: 42
//=> [klona] before: 42
//=> [klona] after: 42
```

**Comment by TrySound** [comment]
Awesome! Thank you!
