### ISSUE TITLE
[TypeScript] Incorrectly declared types

### ISSUE THREAD

**Issue by hakimio** [lukeed/klona#18]
The current type definition results in an error when using library with TypeScript:
`TypeError: klona.default is not a function`

To fix this error, type definitions should be changed to the following:
```ts
export = klona;
declare function klona<T>(val: T): T
```
Just like [dayjs does it](https://github.com/iamkun/dayjs/blob/dev/types/index.d.ts#L3).
[More info](https://github.com/middyjs/middy/issues/203) about the error.

**Comment by hakimio** [comment]
Now trying to import klona, results in an error saying: `This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export`. The fix didn't fix anything.

**Comment by lukeed** [comment]
It did fix things in some instances -- but it broke others. Will be addressed in next release.
