### ISSUE TITLE
klona/full seems discarding prototype properties from class

### ISSUE THREAD

**Issue by otakustay** [lukeed/klona#24]
```js
const clone = require('clone');
const {klona} = require('klona');
const {klona: klonaFull} = require('klona/full');

function MyPlugin() {
}

MyPlugin.prototype = {
    install: function() {
        console.log('install');
    }
}

const options = {
    plugin: new MyPlugin(),
};

console.log('oringinal', options.plugin.install);
console.log('clone', clone(options).plugin.install);
console.log('klona', klona(options).plugin.install);
console.log('klona/full', klonaFull(options).plugin.install);
```

Output:

```shell
oringinal [Function: install]
clone [Function: install]
klona [Function: install]
klona/full undefined
```

Wondering its a bug or is by design, this issue makes [less-loader](https://github.com/webpack-contrib/less-loader/blob/master/src/utils.js#L144) lost less plugin methods.

**Comment by lukeed** [comment]
Hey, thanks for this. Good catch!

Started looking at this tonight and will hopefully have it done tomorrow. The fix is easy but trying to prevent much performance degradation

**Comment by lukeed** [comment]
If you're around, I'd appreciate it if you could check out the `klona/full` changes and verify that it works for you before I publish a new version. I think it covers this issue, but doesn't hurt to verify :D 

Thanks!

**Comment by otakustay** [comment]
Worked in my case (less-loader with less-plugin-functions), great!

**Comment by lukeed** [comment]
Cool, publishing now then
