### ISSUE TITLE
Additional types

### ISSUE THREAD

**Issue by icebob** [lukeed/klona#4]
Great job again, @lukeed!

By the way, do you plan to extend with additional common types, like `Date`, `Buffer`, `Map`, `Set`?

**Comment by lukeed** [comment]
Thanks! Date is already covered. I'll look into the others today

**Comment by icebob** [comment]
Really, sry :)

**Comment by lukeed** [comment]
All good, haha

**Comment by lukeed** [comment]
Closed via ed836c5 and 33c49a4

Thanks!

**Comment by icebob** [comment]
Good job, thanks!
