### ISSUE TITLE
Function call on mutable `constructor` property 

### ISSUE THREAD

**Issue by josebreijo** [lukeed/klona#6]
I know this is a weird edge case, but since `Object.prototype.constructor` [is mutable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor), shouldn't a check be done for the proper constructor before calling it?

https://github.com/lukeed/klona/blob/c969b506c4ecf5677050b671ae65e87e49f4facb/src/index.js#L32-L34

**Comment by lukeed** [comment]
I think this is okay? But I could certainly be wrong.

The `str` is set from `Object.prototype.toString` which doesn't relying on the `constructor` or `constructor.name` values:

```js
class Foo {
  constructor(x) {
    this.name = 'Foo';
      console.log('hello Foo', x)
    }
}

const aaa = new Foo(123)
// => logs: 'hello Foo 123'
// => Foo { name: 'Foo' }

aaa.constructor.name;
//=> 'Foo'

aaa.__proto__;
//=> Foo {}

Object.prototype.toString.call(aaa);
//=> '[object Object]'
```

There _is_ a way to modify that `[object <type>]` value, but it's not through the constructor.

...It probably should be changed but I've got to think on it a little bit. Currently chasing an answer to your other question 😄

**Comment by lukeed** [comment]
I'm taking comfort in knowing that lodash is also using the constructor approach for a lot of their cloning. They've been around long enough & under enough scrutiny for this to have passed the tests of time.

Plus, even if we do something like this instead:

```js
if (str === '[object Int8Array]') return new Int8Array(x);
```

...it can still be spoofed – on both the type match & invoking a function stand-in. Yay JS 😅 

Because of these reasons, I think I'll close this. 
Please let me know if you think I've missed something here!

Thanks~!

**Comment by josebreijo** [comment]
Ohh, maybe I wasn't explicit enough, sorry @lukeed .
I was referring to the fact that you could override the constructor property of an object (in this case a typed array) once created: 

```js
const buf = new ArrayBuffer(8);
const input = new Int32Array(buf);
input.constructor = 'not a function';

klona(input); // this will throw
``` 
<img width="528" alt="Screen Shot 2020-01-10 at 01 11 01" src="https://user-images.githubusercontent.com/30603119/72130024-41a0b580-3346-11ea-8554-8b7aff50b45c.png">

**Comment by lukeed** [comment]
Oh, gotcha. Yeah I'm fine with that. Certain things _should_ throw. The only other alternative is to silently do nothing, which is worse IMO.

FWIW, lodash also throws with the same error. Again, I would expect to see a TypeError _anywhere_ a `constructor` becomes _not_ a constructor.

**Comment by josebreijo** [comment]
When I asked about this, I had in mind finding the proper constructor (from the instance type) and calling it, but now that I think I agree with you, an error is the appropriate response in this scenario. All that extra work will add almost no value and will increase the size. 

Thanks again for the quick replies and for crunching the numbers on the recursion depth question.

**Comment by lukeed** [comment]
It still wouldn't add up though. If you look at the `Foo` example above, it's parsed as `[object Object]`. So even if we saw that Foo had an invalid `constructor`, we'd still be wrong to re-invoke it with `new Object`. It'd avoid an error but produce a mismatch.

You bet! Was fun
