### ISSUE TITLE
Map and Set do not truly deep copy

### ISSUE THREAD

**Issue by GrosSacASac** [lukeed/klona#9]
let original = new Map([["a", {}]])
let c = klona(original)

c.get("a").x = 7
original.get("a").x // 7 oups

**Comment by lukeed** [comment]
Thank you, good catch 👍

**Comment by GrosSacASac** [comment]
Don't close yet, there is still an issue with Map keys, which can be anything including objects and must be klonad to void sharing variables pointers

**Comment by lukeed** [comment]
Ah, right! I never use them that way.

> klonad

😂
